import test from 'node:test';
import assert from 'node:assert/strict';
import { runSmokeTest } from '../src/agent/smoke.js';
import { renderHelp, renderSmoke } from '../src/view/terminal.js';

test('smoke test proves local OpenAI-compatible execution loop', async () => {
  const report = await runSmokeTest();
  assert.equal(report.status, 'pass');
  assert.equal(report.response.status, 200);
  assert.equal(report.upstream.requests.length, 1);
  assert.equal(report.upstream.requests[0].model, report.decision.model.id);
  assert.equal(report.upstream.requests[0].authorization, 'Bearer smoke-key');
  assert.match(report.response.content, /smoke ok/);
  assert.ok(report.routerDecisionMs > 0);
  assert.ok(report.executionMs > 0);
  assert.ok(report.decision.economics.savingsUsd > 0);
  const output = renderSmoke(report);
  assert.match(output, /PROXY SMOKE/);
  assert.match(output, /PASS/);
  assert.match(output, /auth header/);
  assert.match(renderHelp(), /proofroute smoke/);
});

test('smoke test can prove the full transparent proxy entrypoint', async () => {
  const report = await runSmokeTest({ throughProxy: true });
  assert.equal(report.status, 'pass');
  assert.equal(report.mode, 'proxy');
  assert.equal(report.response.status, 200);
  assert.equal(report.upstream.requests.length, 1);
  assert.equal(report.upstream.requests[0].model, report.decision.model.id);
  assert.equal(report.upstream.requests[0].authorization, 'Bearer smoke-key');
  assert.equal(report.response.headers.model, report.decision.model.id);
  assert.equal(report.response.headers.requestedModel, 'smoke-premium');
  assert.equal(report.response.headers.modelSwap, 'true');
  assert.equal(report.response.headers.policy, report.decision.policy);
  assert.equal(report.response.headers.intent, report.decision.intent.name);
  assert.equal(report.response.headers.runnerUp, 'smoke-premium');
  assert.equal(report.response.headers.classifierBackend, 'builtin');
  assert.equal(report.response.headers.classifierCircuit, 'closed');
  assert.equal(report.response.headers.classifierFailures, '0');
  assert.equal(report.response.headers.stream, 'false');
  assert.equal(report.response.headers.usageSource, 'actual');
  assert.ok(Number(report.response.headers.estimatedTokens) > 0);
  assert.equal(report.response.headers.contextWindow, '128000');
  assert.ok(Number(report.response.headers.contextUsePct) > 0);
  assert.ok(Number(report.response.headers.estimatedCostUsd) > 0);
  assert.ok(Number(report.response.headers.baselineCostUsd) > Number(report.response.headers.estimatedCostUsd));
  assert.ok(Number(report.response.headers.estimatedLatencyMs) > 0);
  assert.ok(Number(report.response.headers.baselineLatencyMs) > Number(report.response.headers.estimatedLatencyMs));
  assert.ok(Number(report.response.headers.speedup) > 1);
  assert.ok(Number(report.response.headers.savingsPct) > 0);
  assert.equal(report.response.headers.actualTokens, '13');
  assert.equal(report.response.headers.actualCostUsd, '0.000002');
  assert.ok(Number(report.response.headers.routerOverheadPct) >= 0);
  assert.match(report.response.headers.serverTiming, /proofroute-router;dur=/);
  assert.match(report.response.headers.serverTiming, /proofroute-total;dur=/);
  assert.equal(report.cors.status, 204);
  assert.match(report.cors.exposeHeaders, /server-timing/);
  assert.match(report.cors.allowHeaders, /x-proofroute-policy/);
  assert.match(report.cors.exposeHeaders, /x-proofroute-model/);
  assert.match(report.cors.exposeHeaders, /x-proofroute-requested-model/);
  assert.match(report.cors.exposeHeaders, /x-proofroute-model-swap/);
  assert.match(report.cors.exposeHeaders, /x-proofroute-policy/);
  assert.match(report.cors.exposeHeaders, /x-proofroute-runner-up/);
  assert.match(report.cors.exposeHeaders, /x-proofroute-context-use-pct/);
  assert.match(report.cors.exposeHeaders, /x-proofroute-speedup/);
  assert.match(report.cors.exposeHeaders, /x-proofroute-classifier-backend/);
  assert.match(report.cors.exposeHeaders, /x-proofroute-actual-tokens/);
  assert.match(report.proxy.origin, /^http:\/\/127\.0\.0\.1:/);
  assert.match(report.response.content, /smoke ok/);
  assert.ok(report.routerDecisionMs > 0);
  assert.ok(report.executionMs > 0);
  const output = renderSmoke(report);
  assert.match(output, /transparent/);
  assert.match(output, /browser proof/);
  assert.match(output, /devtools timing/);
  assert.match(output, /usage proof/);
  assert.match(output, /model swap/);
  assert.match(output, /runner-up/);
  assert.match(output, /context use/);
  assert.match(output, /context use\s+0\.09%/);
  assert.match(output, /route cost/);
  assert.match(output, /speed proof/);
  assert.match(output, /speed proof\s+2\.\d+x, saved 98\./);
  assert.match(output, /route overhead/);
  assert.match(output, /proxy cache/);
  assert.match(output, /classifier/);
  assert.match(output, /actual tokens/);
  assert.match(renderHelp(), /proofroute smoke --proxy/);
});

test('proxy smoke matrix proves intent context and cost routing through one entrypoint', async () => {
  const report = await runSmokeTest({ throughProxy: true, matrix: true });
  assert.equal(report.status, 'pass');
  assert.equal(report.mode, 'proxy_matrix');
  assert.equal(report.scenarios.length, 4);
  assert.equal(report.aggregate.passed, 4);
  assert.equal(report.aggregate.count, 4);
  assert.equal(report.ledger.events, 4);
  assert.equal(report.ledger.promptFree, true);
  assert.equal(report.ledger.privacy.status, 'pass');
  assert.equal(report.ledger.privacy.forbiddenMatchCount, 0);
  assert.equal(report.ledger.privacy.parseErrorCount, 0);
  assert.equal(report.upstream.requests.length, 4);
  assert.ok(report.scenarios.every((scenario) => scenario.passed));
  assert.ok(report.scenarios.every((scenario, index) => report.upstream.requests[index].model === scenario.model));
  assert.ok(report.upstream.requests.every((request) => request.authorizationPresent));
  assert.ok(report.upstream.requests.every((request) => request.authorization === undefined));
  assert.ok(report.scenarios.every((scenario) => scenario.modelSwap === 'true'));
  assert.deepEqual(Object.keys(report.aggregate.proofs).sort(), ['context', 'cost', 'intent']);

  const byId = Object.fromEntries(report.scenarios.map((scenario) => [scenario.id, scenario]));
  assert.equal(byId['intent-code'].intent, 'code');
  assert.equal(byId['intent-code'].model, 'smoke-code-pro');
  assert.equal(byId['intent-writing'].intent, 'writing');
  assert.equal(byId['intent-writing'].model, 'smoke-writer-pro');
  assert.notEqual(byId['intent-code'].model, byId['intent-writing'].model);
  assert.equal(byId['context-window'].intent, 'long_context');
  assert.equal(byId['context-window'].model, 'smoke-long-context');
  assert.ok(byId['context-window'].rejectedReasons.includes('context_window'));
  assert.ok(byId['context-window'].rejectedModels.includes('smoke-premium'));
  assert.ok(byId['context-window'].rejectedModels.includes('smoke-code-pro'));
  assert.ok(byId['context-window'].rejectedModels.includes('smoke-writer-pro'));
  assert.ok(byId['context-window'].rejectedModels.includes('smoke-cheap'));
  assert.equal(byId['cost-ceiling'].intent, 'extraction');
  assert.equal(byId['cost-ceiling'].model, 'smoke-cheap');
  assert.ok(byId['cost-ceiling'].rejectedReasons.includes('cost_budget'));
  assert.ok(byId['cost-ceiling'].routeCostUsd <= 0.00003);

  const surface = JSON.stringify(report);
  assert.doesNotMatch(surface, /Refactor this TypeScript|Rewrite this launch|Audit this repository|customer ids|stacktrace|Bearer smoke-key/);
  const output = renderSmoke(report);
  assert.match(output, /PROXY MATRIX/);
  assert.match(output, /same OpenAI-compatible proxy origin/);
  assert.match(output, /ledger proof/);
  assert.match(output, /intent-code/);
  assert.match(output, /context-window/);
  assert.match(output, /cost-ceiling/);
  assert.match(output, /cost_budget/);
  assert.match(renderHelp(), /proofroute smoke --proxy --matrix/);
});
